// ==UserScript==
// @name No Window Open
// @description Blocks window open
// @version 1.3.0
// @author iamogbz
// @homepage https://github.com/iamogbz/oh-my-scripts
// @supportURL https://github.com/iamogbz/oh-my-scripts/issues
// @match *://*/*
// @downloadURL https://github.com/iamogbz/oh-my-scripts/raw/1.3.0/no-window-open.user.js
// @grant none
// @icon https://github.com/iamogbz/oh-my-scripts/raw/main/assets/monkey_128.png
// @namespace iamogbz/oh-my-scripts
// @require https://github.com/iamogbz/oh-my-scripts/raw/1.3.0/lib/dom.js
// @require https://raw.githubusercontent.com/Martii/UserScripts/d8d8829/lib/GM_setStyle/GM_setStyle.js
// @updateURL https://github.com/iamogbz/oh-my-scripts/raw/gh-pages/no-window-open.user.js
// ==/UserScript==

(()=>{"use strict";var e,n={884:(e,n,t)=>{const r=t(6193);!function(){function e(e){return`iamogbz-no-window-open-${e}`}const n=1e4,t=e`popup-element`,o=e`popup-element-link`,i=e`popup-element-close`,a=e`popup-element-visible`,s=`\n#${t} {\n  align-items: center;\n  background-color: #241200EE;\n  border-radius: 4px;\n  bottom: 8px;\n  box-shadow: #00000032 1px 1px 8px;\n  color: white;\n  display: flex;\n  flex-flow: column;\n  font-size: 0.8em;\n  overflow: hidden;\n  padding: 8px;\n  position: fixed;\n  right: -264px;\n  text-align: center;\n  transition: right 0.3s ease;\n  width: 248px;\n}\n\n#${t}.${a} {\n  right: 8px;\n  z-index: ${Number.MAX_SAFE_INTEGER};\n}\n\n#${t} #${i} {\n  background-color: #8d0303EE;\n  border-radius: 2px;\n  border: none;\n  color: white;\n  cursor: pointer;\n  font-size: 0.8em;\n  margin-top: 8px;\n  padding: 4px 6px;\n  width: 100%;\n}\n\n#${t} #${o} {\n  background-color: #0366d6AA;\n  border-radius: 2px;\n  color: white;\n  cursor: pointer;\n  margin-top: 4px;\n  padding: 2px 6px;\n  word-break: break-all;\n}\n`,p="This page just attempted to open a url.\nClick on it below to proceed with navigation.";let l,c;function d(){const e=document.getElementById(t)||(0,r.createElement)({attributes:{id:t},children:[{children:[p],tagName:"div"},{attributes:{id:o,target:"_blank",referrer:"noreferrer"},tagName:"a"},{attributes:{id:i},children:["Dismiss"],events:{click:h},tagName:"button"}],events:{mouseover:m},tagName:"div"});return document.body.appendChild(e),e}function u(){return d().querySelector(`#${o}`)}function f(e){l=e,d(),u().setAttribute("href",e),u().innerHTML=e}function m(){d().classList.add(a),clearTimeout(c),c=setTimeout(h,n)}function h(){d().classList.remove(a)}window.GM_setStyle({data:s}),window.open=function(e){return console.log(`window.open(${e})`),f(e),clearTimeout(c),setTimeout(m,300),{get location(){return{assign:f,close:h,replace:f,get href(){return l},set href(e){f(e)}}},set location(e){e&&("string"==typeof e?f(e):e.href&&f(e.href))}}}}()}},t={};function r(e){var o=t[e];if(void 0!==o)return o.exports;var i=t[e]={exports:{}};return n[e].call(i.exports,i,i.exports,r),i.exports}r.m=n,e=[],r.O=(n,t,o,i)=>{if(!t){var a=1/0;for(c=0;c<e.length;c++){for(var[t,o,i]=e[c],s=!0,p=0;p<t.length;p++)(!1&i||a>=i)&&Object.keys(r.O).every((e=>r.O[e](t[p])))?t.splice(p--,1):(s=!1,i<a&&(a=i));if(s){e.splice(c--,1);var l=o();void 0!==l&&(n=l)}}return n}i=i||0;for(var c=e.length;c>0&&e[c-1][2]>i;c--)e[c]=e[c-1];e[c]=[t,o,i]},r.o=(e,n)=>Object.prototype.hasOwnProperty.call(e,n),(()=>{var e={508:0};r.O.j=n=>0===e[n];var n=(n,t)=>{var o,i,[a,s,p]=t,l=0;if(a.some((n=>0!==e[n]))){for(o in s)r.o(s,o)&&(r.m[o]=s[o]);if(p)var c=p(r)}for(n&&n(t);l<a.length;l++)i=a[l],r.o(e,i)&&e[i]&&e[i][0](),e[i]=0;return r.O(c)},t=self.webpackChunkoh_my_scripts=self.webpackChunkoh_my_scripts||[];t.forEach(n.bind(null,0)),t.push=n.bind(null,t.push.bind(t))})();var o=r.O(void 0,[509],(()=>r(884)));o=r.O(o)})();