name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
      - name: Test
        env:
          CI: true
        run: |
          npm test -- --ci --coverage
      - name: Build
        env:
          NODE_ENV: production
        run: |
          npm run build:compile
          npm run build:package
      - name: Release
        if: github.ref == 'refs/heads/master'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm run release
