name: Build
on:
  pull_request_target:
  push:
    branches:
      - master
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
      - name: Test
        env:
          CI: true
        run: |
          npm test -- --ci --coverage
      - name: Release
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm run release
