on:
  push:
    branches:
    - master
    - gh-pages

jobs:
  retag:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Get Latest Tag
        id: latest_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "::set-output name=tag::$latest_tag"

      - name: Check Existing Tag
        id: check_tag
        run: |
          new_tag=${{ steps.latest_tag.outputs.tag }}
          new_tag=${new_tag#"v"}
          if git rev-parse $new_tag >/dev/null 2>&1; then
            echo "Tag $new_tag already exists"
            echo "::set-output name=tag_exists::true"
          else
            echo "::set-output name=tag_exists::false"
          fi

      - name: Retag Commit
        id: retag
        run: |
          new_tag=${{ steps.latest_tag.outputs.tag }}
          new_tag=${new_tag#"v"}
          if [[ "${{ steps.check_tag.outputs.tag_exists }}" == "true" ]]; then
            echo "Tag $new_tag already exists, skipping retag"
            echo "::set-output name=retag_success::false"
          else
            git tag -d ${{ steps.latest_tag.outputs.tag }}
            git tag $new_tag
            echo "::set-output name=retag_success::true"
          fi

      - name: Push Tag
        if: steps.retag.outputs.retag_success == 'true'
        run: git push origin ${{ steps.retag.outputs.new_tag }}
